import jsPDF from 'jspdf';
import {
  GeneratedTokens,
  TokenConfig,
  ColorScale,
  ColorShade,
} from './types';
import { hexToRGB } from './colors';

const ALL_SHADES: ColorShade[] = [
  '50', '100', '200', '300', '400', '500',
  '600', '700', '800', '900', '950',
];

const M = 20;
const W = 210;
const H = 297;
const CW = W - M * 2;

function rgb(hex: string): [number, number, number] {
  return hexToRGB(hex);
}

function newPage(doc: jsPDF): number {
  doc.addPage();
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, W, H, 'F');
  return M;
}

function sectionTitle(doc: jsPDF, title: string, y: number): number {
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(24, 24, 27);
  doc.text(title, M, y + 6);
  return y + 16;
}

function checkPage(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > H - M) return newPage(doc);
  return y;
}

export function exportAsPDF(tokens: GeneratedTokens, config: TokenConfig) {
  const doc = new jsPDF('p', 'mm', 'a4');
  const [pr, pg, pb] = rgb(config.primaryColor);

  // ───────────── COVER ─────────────
  doc.setFillColor(9, 9, 11);
  doc.rect(0, 0, W, H, 'F');

  doc.setFillColor(pr, pg, pb);
  doc.rect(0, 0, 3, H, 'F');

  doc.setTextColor(244, 244, 245);
  doc.setFontSize(42);
  doc.setFont('helvetica', 'bold');
  doc.text('TokenLab', M, 60);

  doc.setFontSize(16);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(161, 161, 170);
  doc.text('Design Token Documentation', M, 72);

  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const meta = [
    ['Generated', date],
    ['Font', config.fontFamily],
    ['Scale', String(config.scaleRatio)],
    ['Radius', config.radiusStyle],
    ['Base Size', `${config.baseFontSize}px`],
    ['Spacing', `${config.baseSpacing}px`],
  ];

  doc.setFontSize(9);
  let my = 95;
  meta.forEach(([label, value]) => {
    doc.setTextColor(82, 82, 91);
    doc.setFont('helvetica', 'normal');
    doc.text(label, M, my);
    doc.setTextColor(161, 161, 170);
    doc.text(value, M + 28, my);
    my += 7;
  });

  let cx = M;
  const cy = my + 14;
  for (const shade of ['100', '300', '500', '700', '900'] as ColorShade[]) {
    doc.setFillColor(...rgb(tokens.colors.primary[shade]));
    doc.circle(cx + 5, cy, 5, 'F');
    cx += 14;
  }
  cx += 6;
  for (const shade of ['100', '300', '500', '700', '900'] as ColorShade[]) {
    doc.setFillColor(...rgb(tokens.colors.secondary[shade]));
    doc.circle(cx + 5, cy, 5, 'F');
    cx += 14;
  }

  doc.setFontSize(7);
  doc.setTextColor(50, 50, 56);
  doc.text(
    'Generated by TokenLab — tokenlab-gold.vercel.app',
    M,
    H - 15
  );

  // ───────────── COLORS ─────────────
  let y = newPage(doc);
  y = sectionTitle(doc, 'Color System', y);
  y += 2;

  const swatchW = CW / 11;

  for (const [name, scale] of Object.entries(tokens.colors)) {
    y = checkPage(doc, y, 28);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(24, 24, 27);
    doc.text(name.charAt(0).toUpperCase() + name.slice(1), M, y);
    y += 4;

    ALL_SHADES.forEach((shade, i) => {
      const hex = (scale as ColorScale)[shade];
      doc.setFillColor(...rgb(hex));
      doc.roundedRect(M + i * swatchW, y, swatchW - 0.6, 9, 1, 1, 'F');
    });
    y += 11;

    doc.setFontSize(4.5);
    ALL_SHADES.forEach((shade, i) => {
      doc.setTextColor(120, 120, 130);
      doc.text(shade, M + i * swatchW + 0.5, y);
    });
    y += 3.5;

    ALL_SHADES.forEach((shade, i) => {
      const hex = (scale as ColorScale)[shade];
      doc.setTextColor(160, 160, 170);
      doc.text(hex.toUpperCase(), M + i * swatchW + 0.5, y);
    });
    y += 8;
  }

  // ───────────── TYPOGRAPHY ─────────────
  y = newPage(doc);
  y = sectionTitle(doc, 'Typography Scale', y);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(113, 113, 122);
  doc.text(
    `${config.fontFamily}  ·  Ratio ${config.scaleRatio}  ·  Base ${config.baseFontSize}px`,
    M,
    y
  );
  y += 10;

  const tCols = [M, M + 18, M + 48, M + 80, M + 108, M + 140];
  doc.setFontSize(6.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(130, 130, 140);
  ['NAME', 'SIZE (PX)', 'REM', 'WEIGHT', 'LINE-HEIGHT', 'SPACING'].forEach(
    (h, i) => doc.text(h, tCols[i], y)
  );
  y += 1.5;
  doc.setDrawColor(230, 230, 235);
  doc.line(M, y, M + CW, y);
  y += 5;

  for (const step of [...tokens.typography].reverse()) {
    y = checkPage(doc, y, 8);
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(24, 24, 27);
    doc.text(step.name, tCols[0], y);
    doc.setFont('helvetica', 'normal');
    doc.text(`${step.sizePx}`, tCols[1], y);
    doc.text(step.size, tCols[2], y);
    doc.text(String(step.weight), tCols[3], y);
    doc.text(step.lineHeight, tCols[4], y);
    doc.setTextColor(130, 130, 140);
    doc.text(step.letterSpacing, tCols[5], y);
    y += 7.5;
  }

  // ───────────── SPACING ─────────────
  y += 6;
  y = checkPage(doc, y, 100);
  y = sectionTitle(doc, 'Spacing Scale', y);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(113, 113, 122);
  doc.text(`Base unit: ${config.baseSpacing}px`, M, y);
  y += 10;

  doc.setFontSize(6.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(130, 130, 140);
  doc.text('NAME', M, y);
  doc.text('REM', M + 16, y);
  doc.text('PIXELS', M + 50, y);
  y += 1.5;
  doc.setDrawColor(230, 230, 235);
  doc.line(M, y, M + 80, y);
  y += 5;

  for (const step of tokens.spacing.filter((s) => s.px > 0 && s.px <= 96)) {
    y = checkPage(doc, y, 6);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(24, 24, 27);
    doc.text(step.name, M, y);
    doc.setFont('helvetica', 'normal');
    doc.text(step.value, M + 16, y);
    doc.setTextColor(113, 113, 122);
    doc.text(`${step.px}px`, M + 50, y);

    const barW = Math.min(step.px * 0.5, 80);
    if (barW > 0) {
      doc.setFillColor(pr, pg, pb);
      doc.roundedRect(M + 70, y - 2, barW, 2.5, 0.5, 0.5, 'F');
    }
    y += 5.5;
  }

  // ───────────── SHADOWS ─────────────
  y += 8;
  y = checkPage(doc, y, 60);
  y = sectionTitle(doc, 'Shadows', y);
  y += 2;

  for (const step of tokens.shadows) {
    y = checkPage(doc, y, 12);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(24, 24, 27);
    doc.text(step.name, M, y);
    doc.setFontSize(6.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(113, 113, 122);
    doc.text(step.value, M + 14, y);
    y += 7;
  }

  // ───────────── RADIUS ─────────────
  y += 8;
  y = checkPage(doc, y, 60);
  y = sectionTitle(doc, 'Border Radius', y);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(113, 113, 122);
  doc.text(`Style: ${config.radiusStyle}`, M, y);
  y += 10;

  for (const step of tokens.radius) {
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(24, 24, 27);
    doc.text(step.name, M, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(113, 113, 122);
    doc.text(step.value, M + 22, y);
    y += 6;
  }

  doc.save('tokenlab-design-tokens.pdf');
}
